config/routes.rb
Todo::Application.routes.draw do
  resources :lists do
    resources :items
  end

  match '/' => 'lists#index'
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :list
end

app/models/list.rb
class List < ActiveRecord::Base
  has_many :items
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_filter :find_list
  
  def create
    @item = @list.items.new(params[:item])

    respond_to do |format|
      if @item.save
        flash[:notice] = 'Item added!'
        format.html { redirect_to(@list) }
        format.xml  { render :xml => @item, :status => :created, :location => @item }
      else
        flash[:notice] = 'Item could not be added!'
        format.html { redirect_to(@list) }
        format.xml  { render :xml => @item.errors, :status => :unprocessable_entity }
      end
    end
  end

  def destroy
    @item = @list.items.find(params[:id])
    @item.destroy
    flash[:notice] = 'Item completed!'

    respond_to do |format|
      format.html { redirect_to(@list) }
      format.xml  { head :ok }
    end
  end
  
private
  def find_list
    @list = List.find(params[:list_id])
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @lists }
    end
  end

  def show
    @list = List.find(params[:id])
    @new_item = @list.items.new
    
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @list }
    end
  end

  def new
    @list = List.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @list }
    end
  end

  def create
    @list = List.new(params[:list])

    respond_to do |format|
      if @list.save
        flash[:notice] = 'List was successfully created.'
        format.html { redirect_to(@list) }
        format.xml  { render :xml => @list, :status => :created, :location => @list }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @list.errors, :status => :unprocessable_entity }
      end
    end
  end

  def destroy
    @list = List.find(params[:id])
    @list.destroy

    respond_to do |format|
      format.html { redirect_to(lists_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
       "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
  <meta http-equiv="content-type" content="text/html;charset=UTF-8" />
  <title>Listy McGee</title>
  <%= stylesheet_link_tag 'style' %>
</head>
<body>

<p style="color: green"><%= flash[:notice] %></p>

<%= yield %>

</body>
</html>

app/views/lists/index.html.erb
<h1>Your lists</h1>
<hr noshade />

<% @lists.each do |list| %>
  <h2><%= link_to list.name, list %></h2>
  <p><%= list.items.size %> items</p>
  <hr noshade />
<% end %>

<%= link_to 'Create a list', new_list_path %>

app/views/lists/new.html.erb
<h1>Create a list</h1>

<%= form_for(@list) do |f| %>
  <%= f.error_messages %>

  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.submit 'Create list' %> or <%= link_to 'Cancel', lists_path %>
  </p>
<% end %>

app/views/lists/show.html.erb
<h1><%=h @list.name %></h1>

<% if @list.items.blank? %>
  <em>No items in this list</em>
<% else %>
  <ul>
    <% @list.items.each do |item| %>
      <li><%= item.text %> [<%= link_to 'complete', list_item_path(@list, item), :method => :delete %>]</li>
    <% end %>
  </ul>
<% end %>

<hr noshade />

<p>Add item:</p>

<%= form_for([@list, @new_item]) do |f| %>
  <%= f.text_field :text %>
  
  <%= f.submit "Add" %>
<% end %>

<hr noshade />
<%= link_to 'Return to list index', lists_path %>